FROM proteowizard/pwiz-skyline-i-agree-to-the-vendor-licenses:latest

# Make wineprefix world-accessible for any user to use wine
RUN chown -R 1000:1000 /wineprefix64 2>/dev/null || true \
    && chmod -R 777 /wineprefix64

# Copy msconvert script
COPY scripts/msconvert-raw.sh /opt/scripts/msconvert-raw.sh
RUN chmod a+rx /opt/scripts/msconvert-raw.sh

# Keep wine environment variables
ENV WINEPREFIX=/wineprefix64
ENV WINEARCH=win64
ENV WINEDEBUG=-all
