cwlVersion: v1.2
class: CommandLineTool

label: Filter Peptides Present In Control
doc: |
  Keep tumor-specific peptide rows by excluding canonical Protein entries
  (sp| or tr| in the Protein column), then remove rows whose peptide sequence
  exactly matches or is contained in a control combined_peptide.tsv reference.

baseCommand: [python3, /opt/scripts/filter-control-peptides.py]

requirements:
  InlineJavascriptRequirement: {}
  DockerRequirement:
    dockerPull: "pgc-images.sbgenomics.com/childrens-bti/fragpipe_cwl:latest"
  InitialWorkDirRequirement:
    listing:
      - $(inputs.input_combined_peptide)
      - $(inputs.control_combined_peptide)

inputs:
  input_combined_peptide:
    type: File
    doc: Combined peptide table generated by FragPipe for current run
    inputBinding:
      position: 1

  control_combined_peptide:
    type: File
    doc: Combined peptide table from control runs used for overlap filtering
    inputBinding:
      position: 2

  output_basename:
    type: string
    doc: Base name used for output filenames
    inputBinding:
      position: 3

outputs:
  filtered_combined_peptide:
    type: File
    outputBinding:
      glob: "$(inputs.output_basename)_combined_peptide_control_filtered.tsv"
    doc: Tumor-specific combined peptide table after removing peptides found in control

  input_tumor_specific_peptides:
    type: File
    outputBinding:
      glob: "$(inputs.output_basename)_input_tumor_specific_peptides.tsv"
    doc: Input-run tumor-specific peptide rows (non-canonical, non-decoy)

  control_tumor_specific_peptides:
    type: File
    outputBinding:
      glob: "$(inputs.output_basename)_control_tumor_specific_peptides.tsv"
    doc: Control-run tumor-specific peptide rows (non-canonical, non-decoy)

  control_overlap_summary:
    type: File
    outputBinding:
      glob: "$(inputs.output_basename)_control_overlap_summary.txt"
    doc: Summary statistics for control-overlap filtering